# Generated by Django 4.2.4 on 2023-09-05 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bplan", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bplan",
            new_name="bplan_bplan_bbg_anf_1a40f5_idx",
            old_fields=("bbg_anfang", "bbg_ende"),
        ),
        migrations.RenameIndex(
            model_name="bplan",
            new_name="bplan_bplan_aul_anf_fb260f_idx",
            old_fields=("aul_anfang", "aul_ende"),
        ),
    ]
