# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezirk',
            name='slug',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ortsteil',
            name='bezirk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ortsteile', to='bplan.Bezirk'),
        ),
    ]
