# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 20:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bezirk',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
