# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0002_auto_20160316_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplan',
            name='aul_anfang',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='aul_ende',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='bbg_anfang',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='bbg_ende',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='bplan',
            index_together=set([('aul_anfang', 'aul_ende'), ('bbg_anfang', 'bbg_ende')]),
        ),
    ]
