# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='gml_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bezirk',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='bplanID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ortsteil',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
