# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0003_auto_20160412_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='ortsteile',
            field=models.ManyToManyField(to='bplan.Ortsteil'),
        ),
        migrations.AddField(
            model_name='ortsteil',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
    ]
