# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0003_auto_20160310_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bplanID', models.CharField(max_length=50)),
                ('planname', models.CharField(max_length=50)),
                ('spatial_alias', models.CharField(max_length=50)),
                ('spatial_name', models.CharField(max_length=50)),
                ('spatial_type', models.CharField(max_length=50)),
                ('multipolygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('bereich', models.TextField()),
                ('afs_behoer', models.CharField(max_length=256)),
                ('afs_beschl', models.DateField(blank=True, null=True)),
                ('afs_l_aend', models.DateField(blank=True, null=True)),
                ('festg', models.BooleanField(default=False)),
                ('festsg_von', models.CharField(max_length=256)),
                ('festsg_am', models.DateField(blank=True, null=True)),
                ('bbg_anfang', models.DateField(blank=True, null=True)),
                ('bbg_ende', models.DateField(blank=True, null=True)),
                ('aul_anfang', models.DateField(blank=True, null=True)),
                ('aul_ende', models.DateField(blank=True, null=True)),
                ('ausleg_www', models.URLField(blank=True, max_length=256, null=True)),
                ('scan_www', models.URLField(blank=True, max_length=256, null=True)),
                ('grund_www', models.URLField(blank=True, max_length=256, null=True)),
                ('gml_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fsg_gvbl_n', models.CharField(blank=True, max_length=50, null=True)),
                ('fsg_gvbl_s', models.CharField(blank=True, max_length=50, null=True)),
                ('fsg_gvbl_d', models.DateField(blank=True, null=True)),
                ('normkontr', models.CharField(blank=True, max_length=50, null=True)),
                ('bezirk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bplan.Bezirk')),
            ],
        ),
    ]
