# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0004_auto_20160420_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='bezirk_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
