# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0004_bplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplan',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
