# Generated by Django 2.2.19 on 2021-03-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0004_change_some_to_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bplan',
            name='spatial_alias',
        ),
        migrations.RemoveField(
            model_name='bplan',
            name='spatial_name',
        ),
        migrations.RemoveField(
            model_name='bplan',
            name='spatial_type',
        ),
    ]
