# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 15:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0005_auto_20160311_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bplan',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='bplan',
            name='lon',
        ),
        migrations.AddField(
            model_name='bplan',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
