# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0005_bplan_bezirk_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('errors', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bplan',
            name='download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bplan.Download'),
        ),
    ]
