# Generated by Django 2.2.20 on 2021-06-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0005_remove_old_fields_from_bplan_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bplan',
            options={'ordering': ['id']},
        ),
    ]
