# Generated by Django 3.2.13 on 2023-05-03 13:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bplan", "0006_add_ordering_to_bplan"),
    ]

    operations = [
        migrations.DeleteModel("Ortsteil"),
        migrations.CreateModel(
            name="Ortsteil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.CharField(max_length=50, default="")),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "bezirk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bplan.Bezirk",
                        related_name="ortsteile",
                    ),
                ),
            ],
        ),
    ]
