# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0006_auto_20160311_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplan',
            name='festsg_von',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
