# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0007_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='ortsteil',
        ),
    ]
