# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0008_remove_address_ortsteil'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='search_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
