# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 12:43
from __future__ import unicode_literals

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0009_address_search_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
