# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 12:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bplan', '0010_auto_20160511_1443'),
    ]

    operations = [
        migrations.RunSQL("select UpdateGeometrySRID('public', 'bplan_bplan', 'point', 25833) ;"),
        migrations.RunSQL("select UpdateGeometrySRID('public', 'bplan_bplan', 'multipolygon', 25833) ;"),
        migrations.RunSQL("select UpdateGeometrySRID('public', 'bplan_address', 'point', 25833) ;"),
        migrations.RunSQL("select UpdateGeometrySRID('public', 'bplan_bezirk', 'polygon', 25833) ;"),
        migrations.RunSQL("select UpdateGeometrySRID('public', 'bplan_ortsteil', 'polygon', 25833) ;"),

        migrations.AlterField(
            model_name='address',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=25833),
        ),
        migrations.AlterField(
            model_name='bezirk',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=25833),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='multipolygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25833),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25833),
        ),
        migrations.AlterField(
            model_name='ortsteil',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=25833),
        ),
    ]
