language: python
dist: bionic
python:
  - "3.6"
node_js:
- '8'
cache:
  pip: true
  npm: true

addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10-postgis-2.4

services:
  - postgresql

install:
  - sudo apt-get install -y gdal-bin

before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database django_zbp;' -U postgres

script:
  - make install
  - $VIRTUAL_ENV/bin/python manage.py makemigrations --dry-run --check --noinput
  - make fixtures

env:
  global:
    DJANGO_SETTINGS_MODULE='django_zbp.settings.travis'
