
language: python
python:
  - "3.6"
cache:
  pip: true
  directories:
    - node_modules
install:
  - apt-get install -y gdal-bin
  - make install
script:
  - python manage.py makemigrations --dry-run --check --noinput
  - venv/bin/python manage.py migrate
  - make fixtures
#after_success:
# - coveralls
