language: python
python:
  - "3.6"

services:
  - postgresql

cache:
  pip: true
  directories:
    - node_modules

install:
  - sudo apt-get install -y gdal-bin
  - make install

before_script:
  - psql -c 'create database django_zbp;' -U postgres
  - psql -U postgres -c "create extension postgis"

script:
  - python manage.py makemigrations --dry-run --check --noinput
  - venv/bin/python manage.py migrate
  - make fixtures

#after_success:
# - coveralls

env:
  global:
    DJANGO_SETTINGS_MODULE='django_zbp.settings.travis'
